### ISSUE TITLE
Installer needs to confirm repo clone state in more detail

### ISSUE THREAD

**Issue by timkinnane** [timkinnane/node-dev-dotfiles#1]
Currently the install script will clone the repo conditionally using the existence of `~/.cfg` as the basis that it hasn't been cloned already. However, if it doesn't successfully clone, that folder will still exist and subsequent installs will incorrectly skip the cloning step.

The cloning step condition needs to be updated to somehow check that the clone was successful, either using something more qualified inside `~/.cfg` or checking for a list of key files inside `~/` that come from the repo.

Usually the clone fails due to some of the files like `~/.zshrc` already existing in the user's home path. So that could be another enhancement on first run, to warn and exit if those files exist and they're not the ones from the repo.

**Comment by taitems** [comment]
This hit me, I've resolved it with `rm -rf ~/.cfg` and re-running it.
